// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package notifications

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_NotificationSettings_8_list)(nil)

type _NotificationSettings_8_list struct {
	list *[]string
}

func (x *_NotificationSettings_8_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_NotificationSettings_8_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_NotificationSettings_8_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_NotificationSettings_8_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_NotificationSettings_8_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message NotificationSettings at list field NotificationTypes as it is not of Message kind"))
}

func (x *_NotificationSettings_8_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_NotificationSettings_8_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_NotificationSettings_8_list) IsValid() bool {
	return x.list != nil
}

var (
	md_NotificationSettings                   protoreflect.MessageDescriptor
	fd_NotificationSettings_index             protoreflect.FieldDescriptor
	fd_NotificationSettings_userAddress       protoreflect.FieldDescriptor
	fd_NotificationSettings_emailEnabled      protoreflect.FieldDescriptor
	fd_NotificationSettings_pushEnabled       protoreflect.FieldDescriptor
	fd_NotificationSettings_smsEnabled        protoreflect.FieldDescriptor
	fd_NotificationSettings_emailAddress      protoreflect.FieldDescriptor
	fd_NotificationSettings_phoneNumber       protoreflect.FieldDescriptor
	fd_NotificationSettings_notificationTypes protoreflect.FieldDescriptor
	fd_NotificationSettings_frequency         protoreflect.FieldDescriptor
	fd_NotificationSettings_creator           protoreflect.FieldDescriptor
)

func init() {
	file_skillchain_notifications_notification_settings_proto_init()
	md_NotificationSettings = File_skillchain_notifications_notification_settings_proto.Messages().ByName("NotificationSettings")
	fd_NotificationSettings_index = md_NotificationSettings.Fields().ByName("index")
	fd_NotificationSettings_userAddress = md_NotificationSettings.Fields().ByName("userAddress")
	fd_NotificationSettings_emailEnabled = md_NotificationSettings.Fields().ByName("emailEnabled")
	fd_NotificationSettings_pushEnabled = md_NotificationSettings.Fields().ByName("pushEnabled")
	fd_NotificationSettings_smsEnabled = md_NotificationSettings.Fields().ByName("smsEnabled")
	fd_NotificationSettings_emailAddress = md_NotificationSettings.Fields().ByName("emailAddress")
	fd_NotificationSettings_phoneNumber = md_NotificationSettings.Fields().ByName("phoneNumber")
	fd_NotificationSettings_notificationTypes = md_NotificationSettings.Fields().ByName("notificationTypes")
	fd_NotificationSettings_frequency = md_NotificationSettings.Fields().ByName("frequency")
	fd_NotificationSettings_creator = md_NotificationSettings.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_NotificationSettings)(nil)

type fastReflection_NotificationSettings NotificationSettings

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	return (*fastReflection_NotificationSettings)(x)
}

func (x *NotificationSettings) slowProtoReflect() protoreflect.Message {
	mi := &file_skillchain_notifications_notification_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_NotificationSettings_messageType fastReflection_NotificationSettings_messageType
var _ protoreflect.MessageType = fastReflection_NotificationSettings_messageType{}

type fastReflection_NotificationSettings_messageType struct{}

func (x fastReflection_NotificationSettings_messageType) Zero() protoreflect.Message {
	return (*fastReflection_NotificationSettings)(nil)
}
func (x fastReflection_NotificationSettings_messageType) New() protoreflect.Message {
	return new(fastReflection_NotificationSettings)
}
func (x fastReflection_NotificationSettings_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_NotificationSettings
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_NotificationSettings) Descriptor() protoreflect.MessageDescriptor {
	return md_NotificationSettings
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_NotificationSettings) Type() protoreflect.MessageType {
	return _fastReflection_NotificationSettings_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_NotificationSettings) New() protoreflect.Message {
	return new(fastReflection_NotificationSettings)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_NotificationSettings) Interface() protoreflect.ProtoMessage {
	return (*NotificationSettings)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_NotificationSettings) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_NotificationSettings_index, value) {
			return
		}
	}
	if x.UserAddress != "" {
		value := protoreflect.ValueOfString(x.UserAddress)
		if !f(fd_NotificationSettings_userAddress, value) {
			return
		}
	}
	if x.EmailEnabled != false {
		value := protoreflect.ValueOfBool(x.EmailEnabled)
		if !f(fd_NotificationSettings_emailEnabled, value) {
			return
		}
	}
	if x.PushEnabled != false {
		value := protoreflect.ValueOfBool(x.PushEnabled)
		if !f(fd_NotificationSettings_pushEnabled, value) {
			return
		}
	}
	if x.SmsEnabled != false {
		value := protoreflect.ValueOfBool(x.SmsEnabled)
		if !f(fd_NotificationSettings_smsEnabled, value) {
			return
		}
	}
	if x.EmailAddress != "" {
		value := protoreflect.ValueOfString(x.EmailAddress)
		if !f(fd_NotificationSettings_emailAddress, value) {
			return
		}
	}
	if x.PhoneNumber != "" {
		value := protoreflect.ValueOfString(x.PhoneNumber)
		if !f(fd_NotificationSettings_phoneNumber, value) {
			return
		}
	}
	if len(x.NotificationTypes) != 0 {
		value := protoreflect.ValueOfList(&_NotificationSettings_8_list{list: &x.NotificationTypes})
		if !f(fd_NotificationSettings_notificationTypes, value) {
			return
		}
	}
	if x.Frequency != "" {
		value := protoreflect.ValueOfString(x.Frequency)
		if !f(fd_NotificationSettings_frequency, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_NotificationSettings_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_NotificationSettings) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "skillchain.notifications.NotificationSettings.index":
		return x.Index != ""
	case "skillchain.notifications.NotificationSettings.userAddress":
		return x.UserAddress != ""
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		return x.EmailEnabled != false
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		return x.PushEnabled != false
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		return x.SmsEnabled != false
	case "skillchain.notifications.NotificationSettings.emailAddress":
		return x.EmailAddress != ""
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		return x.PhoneNumber != ""
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		return len(x.NotificationTypes) != 0
	case "skillchain.notifications.NotificationSettings.frequency":
		return x.Frequency != ""
	case "skillchain.notifications.NotificationSettings.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NotificationSettings) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "skillchain.notifications.NotificationSettings.index":
		x.Index = ""
	case "skillchain.notifications.NotificationSettings.userAddress":
		x.UserAddress = ""
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		x.EmailEnabled = false
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		x.PushEnabled = false
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		x.SmsEnabled = false
	case "skillchain.notifications.NotificationSettings.emailAddress":
		x.EmailAddress = ""
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		x.PhoneNumber = ""
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		x.NotificationTypes = nil
	case "skillchain.notifications.NotificationSettings.frequency":
		x.Frequency = ""
	case "skillchain.notifications.NotificationSettings.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_NotificationSettings) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "skillchain.notifications.NotificationSettings.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "skillchain.notifications.NotificationSettings.userAddress":
		value := x.UserAddress
		return protoreflect.ValueOfString(value)
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		value := x.EmailEnabled
		return protoreflect.ValueOfBool(value)
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		value := x.PushEnabled
		return protoreflect.ValueOfBool(value)
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		value := x.SmsEnabled
		return protoreflect.ValueOfBool(value)
	case "skillchain.notifications.NotificationSettings.emailAddress":
		value := x.EmailAddress
		return protoreflect.ValueOfString(value)
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		value := x.PhoneNumber
		return protoreflect.ValueOfString(value)
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		if len(x.NotificationTypes) == 0 {
			return protoreflect.ValueOfList(&_NotificationSettings_8_list{})
		}
		listValue := &_NotificationSettings_8_list{list: &x.NotificationTypes}
		return protoreflect.ValueOfList(listValue)
	case "skillchain.notifications.NotificationSettings.frequency":
		value := x.Frequency
		return protoreflect.ValueOfString(value)
	case "skillchain.notifications.NotificationSettings.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NotificationSettings) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "skillchain.notifications.NotificationSettings.index":
		x.Index = value.Interface().(string)
	case "skillchain.notifications.NotificationSettings.userAddress":
		x.UserAddress = value.Interface().(string)
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		x.EmailEnabled = value.Bool()
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		x.PushEnabled = value.Bool()
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		x.SmsEnabled = value.Bool()
	case "skillchain.notifications.NotificationSettings.emailAddress":
		x.EmailAddress = value.Interface().(string)
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		x.PhoneNumber = value.Interface().(string)
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		lv := value.List()
		clv := lv.(*_NotificationSettings_8_list)
		x.NotificationTypes = *clv.list
	case "skillchain.notifications.NotificationSettings.frequency":
		x.Frequency = value.Interface().(string)
	case "skillchain.notifications.NotificationSettings.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NotificationSettings) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		if x.NotificationTypes == nil {
			x.NotificationTypes = []string{}
		}
		value := &_NotificationSettings_8_list{list: &x.NotificationTypes}
		return protoreflect.ValueOfList(value)
	case "skillchain.notifications.NotificationSettings.index":
		panic(fmt.Errorf("field index of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.userAddress":
		panic(fmt.Errorf("field userAddress of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		panic(fmt.Errorf("field emailEnabled of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		panic(fmt.Errorf("field pushEnabled of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		panic(fmt.Errorf("field smsEnabled of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.emailAddress":
		panic(fmt.Errorf("field emailAddress of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		panic(fmt.Errorf("field phoneNumber of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.frequency":
		panic(fmt.Errorf("field frequency of message skillchain.notifications.NotificationSettings is not mutable"))
	case "skillchain.notifications.NotificationSettings.creator":
		panic(fmt.Errorf("field creator of message skillchain.notifications.NotificationSettings is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_NotificationSettings) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "skillchain.notifications.NotificationSettings.index":
		return protoreflect.ValueOfString("")
	case "skillchain.notifications.NotificationSettings.userAddress":
		return protoreflect.ValueOfString("")
	case "skillchain.notifications.NotificationSettings.emailEnabled":
		return protoreflect.ValueOfBool(false)
	case "skillchain.notifications.NotificationSettings.pushEnabled":
		return protoreflect.ValueOfBool(false)
	case "skillchain.notifications.NotificationSettings.smsEnabled":
		return protoreflect.ValueOfBool(false)
	case "skillchain.notifications.NotificationSettings.emailAddress":
		return protoreflect.ValueOfString("")
	case "skillchain.notifications.NotificationSettings.phoneNumber":
		return protoreflect.ValueOfString("")
	case "skillchain.notifications.NotificationSettings.notificationTypes":
		list := []string{}
		return protoreflect.ValueOfList(&_NotificationSettings_8_list{list: &list})
	case "skillchain.notifications.NotificationSettings.frequency":
		return protoreflect.ValueOfString("")
	case "skillchain.notifications.NotificationSettings.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.notifications.NotificationSettings"))
		}
		panic(fmt.Errorf("message skillchain.notifications.NotificationSettings does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_NotificationSettings) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in skillchain.notifications.NotificationSettings", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_NotificationSettings) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NotificationSettings) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_NotificationSettings) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_NotificationSettings) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*NotificationSettings)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.UserAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.EmailEnabled {
			n += 2
		}
		if x.PushEnabled {
			n += 2
		}
		if x.SmsEnabled {
			n += 2
		}
		l = len(x.EmailAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PhoneNumber)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.NotificationTypes) > 0 {
			for _, s := range x.NotificationTypes {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.Frequency)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*NotificationSettings)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.Frequency) > 0 {
			i -= len(x.Frequency)
			copy(dAtA[i:], x.Frequency)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Frequency)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.NotificationTypes) > 0 {
			for iNdEx := len(x.NotificationTypes) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.NotificationTypes[iNdEx])
				copy(dAtA[i:], x.NotificationTypes[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NotificationTypes[iNdEx])))
				i--
				dAtA[i] = 0x42
			}
		}
		if len(x.PhoneNumber) > 0 {
			i -= len(x.PhoneNumber)
			copy(dAtA[i:], x.PhoneNumber)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PhoneNumber)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.EmailAddress) > 0 {
			i -= len(x.EmailAddress)
			copy(dAtA[i:], x.EmailAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EmailAddress)))
			i--
			dAtA[i] = 0x32
		}
		if x.SmsEnabled {
			i--
			if x.SmsEnabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x28
		}
		if x.PushEnabled {
			i--
			if x.PushEnabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x20
		}
		if x.EmailEnabled {
			i--
			if x.EmailEnabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x18
		}
		if len(x.UserAddress) > 0 {
			i -= len(x.UserAddress)
			copy(dAtA[i:], x.UserAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.UserAddress)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*NotificationSettings)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: NotificationSettings: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: NotificationSettings: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field UserAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.UserAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EmailEnabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.EmailEnabled = bool(v != 0)
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PushEnabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.PushEnabled = bool(v != 0)
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SmsEnabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.SmsEnabled = bool(v != 0)
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EmailAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EmailAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PhoneNumber", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PhoneNumber = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NotificationTypes", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NotificationTypes = append(x.NotificationTypes, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Frequency = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: skillchain/notifications/notification_settings.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index             string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	UserAddress       string   `protobuf:"bytes,2,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	EmailEnabled      bool     `protobuf:"varint,3,opt,name=emailEnabled,proto3" json:"emailEnabled,omitempty"`
	PushEnabled       bool     `protobuf:"varint,4,opt,name=pushEnabled,proto3" json:"pushEnabled,omitempty"`
	SmsEnabled        bool     `protobuf:"varint,5,opt,name=smsEnabled,proto3" json:"smsEnabled,omitempty"`
	EmailAddress      string   `protobuf:"bytes,6,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	PhoneNumber       string   `protobuf:"bytes,7,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	NotificationTypes []string `protobuf:"bytes,8,rep,name=notificationTypes,proto3" json:"notificationTypes,omitempty"`
	Frequency         string   `protobuf:"bytes,9,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Creator           string   `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skillchain_notifications_notification_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_skillchain_notifications_notification_settings_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationSettings) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *NotificationSettings) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *NotificationSettings) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *NotificationSettings) GetPushEnabled() bool {
	if x != nil {
		return x.PushEnabled
	}
	return false
}

func (x *NotificationSettings) GetSmsEnabled() bool {
	if x != nil {
		return x.SmsEnabled
	}
	return false
}

func (x *NotificationSettings) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *NotificationSettings) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *NotificationSettings) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

func (x *NotificationSettings) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *NotificationSettings) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_skillchain_notifications_notification_settings_proto protoreflect.FileDescriptor

var file_skillchain_notifications_notification_settings_proto_rawDesc = []byte{
	0x0a, 0x34, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0xe0, 0x02, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x75, 0x73, 0x68,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6d, 0x73, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x6d, 0x73,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a,
	0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x42, 0xe3, 0x01, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x42, 0x19, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x27, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0xa2, 0x02, 0x03, 0x53, 0x4e, 0x58,
	0xaa, 0x02, 0x18, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0xca, 0x02, 0x18, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0xe2, 0x02, 0x24, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x5c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x19,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_skillchain_notifications_notification_settings_proto_rawDescOnce sync.Once
	file_skillchain_notifications_notification_settings_proto_rawDescData = file_skillchain_notifications_notification_settings_proto_rawDesc
)

func file_skillchain_notifications_notification_settings_proto_rawDescGZIP() []byte {
	file_skillchain_notifications_notification_settings_proto_rawDescOnce.Do(func() {
		file_skillchain_notifications_notification_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_skillchain_notifications_notification_settings_proto_rawDescData)
	})
	return file_skillchain_notifications_notification_settings_proto_rawDescData
}

var file_skillchain_notifications_notification_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_skillchain_notifications_notification_settings_proto_goTypes = []interface{}{
	(*NotificationSettings)(nil), // 0: skillchain.notifications.NotificationSettings
}
var file_skillchain_notifications_notification_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skillchain_notifications_notification_settings_proto_init() }
func file_skillchain_notifications_notification_settings_proto_init() {
	if File_skillchain_notifications_notification_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_skillchain_notifications_notification_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificationSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skillchain_notifications_notification_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skillchain_notifications_notification_settings_proto_goTypes,
		DependencyIndexes: file_skillchain_notifications_notification_settings_proto_depIdxs,
		MessageInfos:      file_skillchain_notifications_notification_settings_proto_msgTypes,
	}.Build()
	File_skillchain_notifications_notification_settings_proto = out.File
	file_skillchain_notifications_notification_settings_proto_rawDesc = nil
	file_skillchain_notifications_notification_settings_proto_goTypes = nil
	file_skillchain_notifications_notification_settings_proto_depIdxs = nil
}
