// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/notifications/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetNotificationRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetNotificationRequest) Reset()         { *m = QueryGetNotificationRequest{} }
func (m *QueryGetNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotificationRequest) ProtoMessage()    {}
func (*QueryGetNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{2}
}
func (m *QueryGetNotificationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotificationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotificationRequest.Merge(m, src)
}
func (m *QueryGetNotificationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotificationRequest proto.InternalMessageInfo

func (m *QueryGetNotificationRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetNotificationResponse struct {
	Notification Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification"`
}

func (m *QueryGetNotificationResponse) Reset()         { *m = QueryGetNotificationResponse{} }
func (m *QueryGetNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotificationResponse) ProtoMessage()    {}
func (*QueryGetNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{3}
}
func (m *QueryGetNotificationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotificationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotificationResponse.Merge(m, src)
}
func (m *QueryGetNotificationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotificationResponse proto.InternalMessageInfo

func (m *QueryGetNotificationResponse) GetNotification() Notification {
	if m != nil {
		return m.Notification
	}
	return Notification{}
}

type QueryAllNotificationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotificationRequest) Reset()         { *m = QueryAllNotificationRequest{} }
func (m *QueryAllNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotificationRequest) ProtoMessage()    {}
func (*QueryAllNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{4}
}
func (m *QueryAllNotificationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotificationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotificationRequest.Merge(m, src)
}
func (m *QueryAllNotificationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotificationRequest proto.InternalMessageInfo

func (m *QueryAllNotificationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNotificationResponse struct {
	Notification []Notification      `protobuf:"bytes,1,rep,name=notification,proto3" json:"notification"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotificationResponse) Reset()         { *m = QueryAllNotificationResponse{} }
func (m *QueryAllNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotificationResponse) ProtoMessage()    {}
func (*QueryAllNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{5}
}
func (m *QueryAllNotificationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotificationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotificationResponse.Merge(m, src)
}
func (m *QueryAllNotificationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotificationResponse proto.InternalMessageInfo

func (m *QueryAllNotificationResponse) GetNotification() []Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *QueryAllNotificationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetNotificationSettingsRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetNotificationSettingsRequest) Reset()         { *m = QueryGetNotificationSettingsRequest{} }
func (m *QueryGetNotificationSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotificationSettingsRequest) ProtoMessage()    {}
func (*QueryGetNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{6}
}
func (m *QueryGetNotificationSettingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotificationSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotificationSettingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotificationSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotificationSettingsRequest.Merge(m, src)
}
func (m *QueryGetNotificationSettingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotificationSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotificationSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotificationSettingsRequest proto.InternalMessageInfo

func (m *QueryGetNotificationSettingsRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetNotificationSettingsResponse struct {
	NotificationSettings NotificationSettings `protobuf:"bytes,1,opt,name=notificationSettings,proto3" json:"notificationSettings"`
}

func (m *QueryGetNotificationSettingsResponse) Reset()         { *m = QueryGetNotificationSettingsResponse{} }
func (m *QueryGetNotificationSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotificationSettingsResponse) ProtoMessage()    {}
func (*QueryGetNotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{7}
}
func (m *QueryGetNotificationSettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotificationSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotificationSettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotificationSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotificationSettingsResponse.Merge(m, src)
}
func (m *QueryGetNotificationSettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotificationSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotificationSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotificationSettingsResponse proto.InternalMessageInfo

func (m *QueryGetNotificationSettingsResponse) GetNotificationSettings() NotificationSettings {
	if m != nil {
		return m.NotificationSettings
	}
	return NotificationSettings{}
}

type QueryAllNotificationSettingsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotificationSettingsRequest) Reset()         { *m = QueryAllNotificationSettingsRequest{} }
func (m *QueryAllNotificationSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotificationSettingsRequest) ProtoMessage()    {}
func (*QueryAllNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{8}
}
func (m *QueryAllNotificationSettingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotificationSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotificationSettingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotificationSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotificationSettingsRequest.Merge(m, src)
}
func (m *QueryAllNotificationSettingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotificationSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotificationSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotificationSettingsRequest proto.InternalMessageInfo

func (m *QueryAllNotificationSettingsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNotificationSettingsResponse struct {
	NotificationSettings []NotificationSettings `protobuf:"bytes,1,rep,name=notificationSettings,proto3" json:"notificationSettings"`
	Pagination           *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotificationSettingsResponse) Reset()         { *m = QueryAllNotificationSettingsResponse{} }
func (m *QueryAllNotificationSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotificationSettingsResponse) ProtoMessage()    {}
func (*QueryAllNotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c727c5614a3062, []int{9}
}
func (m *QueryAllNotificationSettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotificationSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotificationSettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotificationSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotificationSettingsResponse.Merge(m, src)
}
func (m *QueryAllNotificationSettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotificationSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotificationSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotificationSettingsResponse proto.InternalMessageInfo

func (m *QueryAllNotificationSettingsResponse) GetNotificationSettings() []NotificationSettings {
	if m != nil {
		return m.NotificationSettings
	}
	return nil
}

func (m *QueryAllNotificationSettingsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "skillchain.notifications.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "skillchain.notifications.QueryParamsResponse")
	proto.RegisterType((*QueryGetNotificationRequest)(nil), "skillchain.notifications.QueryGetNotificationRequest")
	proto.RegisterType((*QueryGetNotificationResponse)(nil), "skillchain.notifications.QueryGetNotificationResponse")
	proto.RegisterType((*QueryAllNotificationRequest)(nil), "skillchain.notifications.QueryAllNotificationRequest")
	proto.RegisterType((*QueryAllNotificationResponse)(nil), "skillchain.notifications.QueryAllNotificationResponse")
	proto.RegisterType((*QueryGetNotificationSettingsRequest)(nil), "skillchain.notifications.QueryGetNotificationSettingsRequest")
	proto.RegisterType((*QueryGetNotificationSettingsResponse)(nil), "skillchain.notifications.QueryGetNotificationSettingsResponse")
	proto.RegisterType((*QueryAllNotificationSettingsRequest)(nil), "skillchain.notifications.QueryAllNotificationSettingsRequest")
	proto.RegisterType((*QueryAllNotificationSettingsResponse)(nil), "skillchain.notifications.QueryAllNotificationSettingsResponse")
}

func init() {
	proto.RegisterFile("skillchain/notifications/query.proto", fileDescriptor_01c727c5614a3062)
}

var fileDescriptor_01c727c5614a3062 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0xcf, 0xb4, 0x36, 0xd2, 0xb1, 0x20, 0x8e, 0x01, 0x4b, 0x2c, 0x6b, 0x18, 0x6b, 0x0d, 0x55,
	0x77, 0x4c, 0xab, 0x2d, 0x2a, 0x55, 0x1a, 0xc1, 0xde, 0x24, 0xc6, 0x5b, 0x2f, 0x32, 0x89, 0xe3,
	0x76, 0x71, 0x33, 0xb3, 0xcd, 0x4e, 0xa5, 0x45, 0xbc, 0xf8, 0x05, 0x2c, 0xf8, 0x25, 0x3c, 0xd6,
	0x83, 0x07, 0xbf, 0x41, 0x8f, 0x15, 0x41, 0xf4, 0x22, 0x92, 0x08, 0x7e, 0x0d, 0xc9, 0xcc, 0xa4,
	0xdd, 0xa4, 0xbb, 0xdd, 0x5d, 0xcd, 0x25, 0xec, 0x9f, 0xf7, 0xde, 0xef, 0xcf, 0x7b, 0xf3, 0xb2,
	0x70, 0x36, 0x78, 0xe9, 0x7a, 0x5e, 0x73, 0x83, 0xba, 0x9c, 0x70, 0x21, 0xdd, 0x17, 0x6e, 0x93,
	0x4a, 0x57, 0xf0, 0x80, 0x6c, 0x6e, 0xb1, 0xf6, 0x8e, 0xed, 0xb7, 0x85, 0x14, 0x68, 0xfa, 0x28,
	0xca, 0x1e, 0x88, 0x2a, 0x9e, 0xa3, 0x2d, 0x97, 0x0b, 0xa2, 0x7e, 0x75, 0x70, 0xb1, 0xe0, 0x08,
	0x47, 0xa8, 0x4b, 0xd2, 0xbb, 0x32, 0x4f, 0x67, 0x1c, 0x21, 0x1c, 0x8f, 0x11, 0xea, 0xbb, 0x84,
	0x72, 0x2e, 0xa4, 0x2e, 0x60, 0xde, 0xce, 0x37, 0x45, 0xd0, 0x12, 0x01, 0x69, 0xd0, 0x80, 0x69,
	0x64, 0xf2, 0xaa, 0xd2, 0x60, 0x92, 0x56, 0x88, 0x4f, 0x1d, 0x97, 0xab, 0x60, 0x13, 0x7b, 0x25,
	0x96, 0xb2, 0x4f, 0xdb, 0xb4, 0xd5, 0x2f, 0x79, 0x2d, 0x36, 0x2c, 0x7c, 0x67, 0x82, 0x6f, 0xa5,
	0x0a, 0x7e, 0x16, 0x30, 0x29, 0x5d, 0xee, 0x18, 0x08, 0x5c, 0x80, 0xe8, 0x49, 0x8f, 0x6b, 0x4d,
	0xe1, 0xd6, 0xd9, 0xe6, 0x16, 0x0b, 0x24, 0x5e, 0x87, 0xe7, 0x07, 0x9e, 0x06, 0xbe, 0xe0, 0x01,
	0x43, 0x0f, 0x61, 0x5e, 0xf3, 0x9b, 0x06, 0x25, 0x50, 0x3e, 0xb3, 0x50, 0xb2, 0xe3, 0x4c, 0xb5,
	0x75, 0x66, 0x75, 0x72, 0xff, 0xe7, 0xa5, 0xdc, 0x87, 0x3f, 0x7b, 0xf3, 0xa0, 0x6e, 0x52, 0xf1,
	0x22, 0xbc, 0xa8, 0x6a, 0xaf, 0x31, 0xf9, 0x38, 0x94, 0x62, 0xa0, 0x51, 0x01, 0x4e, 0xb8, 0xfc,
	0x39, 0xdb, 0x56, 0x10, 0x93, 0x75, 0x7d, 0x83, 0x7d, 0x38, 0x13, 0x9d, 0x64, 0x98, 0xd5, 0xe0,
	0x54, 0x18, 0xdf, 0xf0, 0x9b, 0x8b, 0xe7, 0x17, 0xae, 0x52, 0x3d, 0xd5, 0x63, 0x59, 0x1f, 0xa8,
	0x80, 0x99, 0xa1, 0xb9, 0xea, 0x79, 0x51, 0x34, 0x1f, 0x41, 0x78, 0xd4, 0xd5, 0x43, 0x38, 0x3d,
	0x02, 0x76, 0x6f, 0x04, 0x6c, 0x3d, 0x7c, 0x66, 0x04, 0xec, 0x1a, 0x75, 0x98, 0xc9, 0xad, 0x87,
	0x32, 0xf1, 0x67, 0x60, 0x94, 0x1d, 0xc3, 0x89, 0x55, 0x36, 0xfe, 0x7f, 0xca, 0xd0, 0xda, 0x00,
	0xf5, 0x31, 0x45, 0xfd, 0x6a, 0x22, 0x75, 0x4d, 0x67, 0x80, 0xfb, 0x3d, 0x78, 0x39, 0xaa, 0x29,
	0x4f, 0xcd, 0x84, 0x9d, 0xdc, 0xd1, 0x5d, 0x00, 0x67, 0x4f, 0xce, 0x36, 0x06, 0x6c, 0xc0, 0x02,
	0x8f, 0x78, 0x6f, 0x3c, 0xb7, 0xd3, 0x19, 0xd1, 0xcf, 0x32, 0x86, 0x44, 0x56, 0xc4, 0x2d, 0xa3,
	0x67, 0xa8, 0x15, 0xc3, 0x7a, 0x46, 0xd5, 0xfa, 0x1f, 0x7d, 0x07, 0x62, 0xf1, 0x12, 0x1d, 0x18,
	0x1f, 0xad, 0x03, 0x23, 0x1b, 0x8d, 0x85, 0x8f, 0xa7, 0xe1, 0x84, 0xd2, 0x86, 0xde, 0x01, 0x98,
	0xd7, 0xcb, 0x00, 0x5d, 0x8f, 0x67, 0x7a, 0x7c, 0x07, 0x15, 0x6f, 0xa4, 0x8c, 0xd6, 0xe8, 0xb8,
	0xfc, 0xf6, 0xeb, 0xef, 0xf7, 0x63, 0x18, 0x95, 0x48, 0xc2, 0x6e, 0x45, 0x9f, 0x00, 0x9c, 0x0a,
	0x3b, 0x83, 0x6e, 0x27, 0x20, 0x45, 0x6f, 0xaa, 0xe2, 0x52, 0xd6, 0x34, 0xc3, 0x74, 0x49, 0x31,
	0xbd, 0x89, 0x6c, 0x92, 0x6a, 0x63, 0x93, 0xd7, 0xea, 0xc0, 0xbc, 0x41, 0x7b, 0x00, 0x9e, 0x0d,
	0x17, 0x5c, 0xf5, 0xbc, 0x44, 0xea, 0xd1, 0xdb, 0x2b, 0x91, 0x7a, 0xcc, 0x32, 0xc2, 0xb6, 0xa2,
	0x5e, 0x46, 0x73, 0xe9, 0xa8, 0xa3, 0x6f, 0x00, 0x16, 0xa2, 0x86, 0x10, 0xad, 0x64, 0xf3, 0x6e,
	0xe8, 0x08, 0x16, 0xef, 0xff, 0x6b, 0xba, 0xd1, 0xf1, 0x40, 0xe9, 0xb8, 0x83, 0x96, 0x49, 0xb6,
	0x3f, 0xcd, 0xc3, 0x5e, 0x7c, 0x01, 0xf0, 0x42, 0x14, 0x42, 0xaf, 0x27, 0x2b, 0xd9, 0xcc, 0xcd,
	0xaa, 0x2d, 0x61, 0x5b, 0xe0, 0x65, 0xa5, 0xad, 0x82, 0x48, 0x46, 0x6d, 0xd5, 0xbb, 0xfb, 0x1d,
	0x0b, 0x1c, 0x74, 0x2c, 0xf0, 0xab, 0x63, 0x81, 0xdd, 0xae, 0x95, 0x3b, 0xe8, 0x5a, 0xb9, 0xef,
	0x5d, 0x2b, 0xb7, 0x5e, 0x0a, 0x55, 0xda, 0x1e, 0xaa, 0x25, 0x77, 0x7c, 0x16, 0x34, 0xf2, 0xea,
	0x6b, 0x62, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x1a, 0x29, 0xae, 0x8c, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Notification items.
	Notification(ctx context.Context, in *QueryGetNotificationRequest, opts ...grpc.CallOption) (*QueryGetNotificationResponse, error)
	NotificationAll(ctx context.Context, in *QueryAllNotificationRequest, opts ...grpc.CallOption) (*QueryAllNotificationResponse, error)
	// Queries a list of NotificationSettings items.
	NotificationSettings(ctx context.Context, in *QueryGetNotificationSettingsRequest, opts ...grpc.CallOption) (*QueryGetNotificationSettingsResponse, error)
	NotificationSettingsAll(ctx context.Context, in *QueryAllNotificationSettingsRequest, opts ...grpc.CallOption) (*QueryAllNotificationSettingsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/skillchain.notifications.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Notification(ctx context.Context, in *QueryGetNotificationRequest, opts ...grpc.CallOption) (*QueryGetNotificationResponse, error) {
	out := new(QueryGetNotificationResponse)
	err := c.cc.Invoke(ctx, "/skillchain.notifications.Query/Notification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NotificationAll(ctx context.Context, in *QueryAllNotificationRequest, opts ...grpc.CallOption) (*QueryAllNotificationResponse, error) {
	out := new(QueryAllNotificationResponse)
	err := c.cc.Invoke(ctx, "/skillchain.notifications.Query/NotificationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NotificationSettings(ctx context.Context, in *QueryGetNotificationSettingsRequest, opts ...grpc.CallOption) (*QueryGetNotificationSettingsResponse, error) {
	out := new(QueryGetNotificationSettingsResponse)
	err := c.cc.Invoke(ctx, "/skillchain.notifications.Query/NotificationSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NotificationSettingsAll(ctx context.Context, in *QueryAllNotificationSettingsRequest, opts ...grpc.CallOption) (*QueryAllNotificationSettingsResponse, error) {
	out := new(QueryAllNotificationSettingsResponse)
	err := c.cc.Invoke(ctx, "/skillchain.notifications.Query/NotificationSettingsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Notification items.
	Notification(context.Context, *QueryGetNotificationRequest) (*QueryGetNotificationResponse, error)
	NotificationAll(context.Context, *QueryAllNotificationRequest) (*QueryAllNotificationResponse, error)
	// Queries a list of NotificationSettings items.
	NotificationSettings(context.Context, *QueryGetNotificationSettingsRequest) (*QueryGetNotificationSettingsResponse, error)
	NotificationSettingsAll(context.Context, *QueryAllNotificationSettingsRequest) (*QueryAllNotificationSettingsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Notification(ctx context.Context, req *QueryGetNotificationRequest) (*QueryGetNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notification not implemented")
}
func (*UnimplementedQueryServer) NotificationAll(ctx context.Context, req *QueryAllNotificationRequest) (*QueryAllNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificationAll not implemented")
}
func (*UnimplementedQueryServer) NotificationSettings(ctx context.Context, req *QueryGetNotificationSettingsRequest) (*QueryGetNotificationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificationSettings not implemented")
}
func (*UnimplementedQueryServer) NotificationSettingsAll(ctx context.Context, req *QueryAllNotificationSettingsRequest) (*QueryAllNotificationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificationSettingsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.notifications.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Notification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Notification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.notifications.Query/Notification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Notification(ctx, req.(*QueryGetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NotificationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NotificationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.notifications.Query/NotificationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NotificationAll(ctx, req.(*QueryAllNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NotificationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NotificationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.notifications.Query/NotificationSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NotificationSettings(ctx, req.(*QueryGetNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NotificationSettingsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNotificationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NotificationSettingsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.notifications.Query/NotificationSettingsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NotificationSettingsAll(ctx, req.(*QueryAllNotificationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skillchain.notifications.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Notification",
			Handler:    _Query_Notification_Handler,
		},
		{
			MethodName: "NotificationAll",
			Handler:    _Query_NotificationAll_Handler,
		},
		{
			MethodName: "NotificationSettings",
			Handler:    _Query_NotificationSettings_Handler,
		},
		{
			MethodName: "NotificationSettingsAll",
			Handler:    _Query_NotificationSettingsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skillchain/notifications/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNotificationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotificationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotificationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNotificationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotificationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotificationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Notification.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllNotificationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotificationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotificationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNotificationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotificationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotificationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Notification) > 0 {
		for iNdEx := len(m.Notification) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Notification[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNotificationSettingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotificationSettingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotificationSettingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNotificationSettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotificationSettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotificationSettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NotificationSettings.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllNotificationSettingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotificationSettingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotificationSettingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNotificationSettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotificationSettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotificationSettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NotificationSettings) > 0 {
		for iNdEx := len(m.NotificationSettings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NotificationSettings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNotificationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNotificationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Notification.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllNotificationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNotificationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Notification) > 0 {
		for _, e := range m.Notification {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNotificationSettingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNotificationSettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NotificationSettings.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllNotificationSettingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNotificationSettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NotificationSettings) > 0 {
		for _, e := range m.NotificationSettings {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotificationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotificationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotificationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotificationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotificationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotificationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Notification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Notification.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotificationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotificationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotificationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotificationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotificationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotificationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Notification", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Notification = append(m.Notification, Notification{})
			if err := m.Notification[len(m.Notification)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotificationSettingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotificationSettingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotificationSettingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotificationSettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotificationSettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotificationSettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotificationSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NotificationSettings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotificationSettingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotificationSettingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotificationSettingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotificationSettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotificationSettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotificationSettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotificationSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NotificationSettings = append(m.NotificationSettings, NotificationSettings{})
			if err := m.NotificationSettings[len(m.NotificationSettings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
