// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/filestorage/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetFileRecordRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetFileRecordRequest) Reset()         { *m = QueryGetFileRecordRequest{} }
func (m *QueryGetFileRecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetFileRecordRequest) ProtoMessage()    {}
func (*QueryGetFileRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{2}
}
func (m *QueryGetFileRecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFileRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFileRecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFileRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFileRecordRequest.Merge(m, src)
}
func (m *QueryGetFileRecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFileRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFileRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFileRecordRequest proto.InternalMessageInfo

func (m *QueryGetFileRecordRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetFileRecordResponse struct {
	FileRecord FileRecord `protobuf:"bytes,1,opt,name=fileRecord,proto3" json:"fileRecord"`
}

func (m *QueryGetFileRecordResponse) Reset()         { *m = QueryGetFileRecordResponse{} }
func (m *QueryGetFileRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetFileRecordResponse) ProtoMessage()    {}
func (*QueryGetFileRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{3}
}
func (m *QueryGetFileRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFileRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFileRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFileRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFileRecordResponse.Merge(m, src)
}
func (m *QueryGetFileRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFileRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFileRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFileRecordResponse proto.InternalMessageInfo

func (m *QueryGetFileRecordResponse) GetFileRecord() FileRecord {
	if m != nil {
		return m.FileRecord
	}
	return FileRecord{}
}

type QueryAllFileRecordRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFileRecordRequest) Reset()         { *m = QueryAllFileRecordRequest{} }
func (m *QueryAllFileRecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllFileRecordRequest) ProtoMessage()    {}
func (*QueryAllFileRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{4}
}
func (m *QueryAllFileRecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFileRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFileRecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFileRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFileRecordRequest.Merge(m, src)
}
func (m *QueryAllFileRecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFileRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFileRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFileRecordRequest proto.InternalMessageInfo

func (m *QueryAllFileRecordRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllFileRecordResponse struct {
	FileRecord []FileRecord        `protobuf:"bytes,1,rep,name=fileRecord,proto3" json:"fileRecord"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFileRecordResponse) Reset()         { *m = QueryAllFileRecordResponse{} }
func (m *QueryAllFileRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllFileRecordResponse) ProtoMessage()    {}
func (*QueryAllFileRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{5}
}
func (m *QueryAllFileRecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFileRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFileRecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFileRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFileRecordResponse.Merge(m, src)
}
func (m *QueryAllFileRecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFileRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFileRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFileRecordResponse proto.InternalMessageInfo

func (m *QueryAllFileRecordResponse) GetFileRecord() []FileRecord {
	if m != nil {
		return m.FileRecord
	}
	return nil
}

func (m *QueryAllFileRecordResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetFilePermissionRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetFilePermissionRequest) Reset()         { *m = QueryGetFilePermissionRequest{} }
func (m *QueryGetFilePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetFilePermissionRequest) ProtoMessage()    {}
func (*QueryGetFilePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{6}
}
func (m *QueryGetFilePermissionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFilePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFilePermissionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFilePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFilePermissionRequest.Merge(m, src)
}
func (m *QueryGetFilePermissionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFilePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFilePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFilePermissionRequest proto.InternalMessageInfo

func (m *QueryGetFilePermissionRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetFilePermissionResponse struct {
	FilePermission FilePermission `protobuf:"bytes,1,opt,name=filePermission,proto3" json:"filePermission"`
}

func (m *QueryGetFilePermissionResponse) Reset()         { *m = QueryGetFilePermissionResponse{} }
func (m *QueryGetFilePermissionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetFilePermissionResponse) ProtoMessage()    {}
func (*QueryGetFilePermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{7}
}
func (m *QueryGetFilePermissionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetFilePermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetFilePermissionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetFilePermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetFilePermissionResponse.Merge(m, src)
}
func (m *QueryGetFilePermissionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetFilePermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetFilePermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetFilePermissionResponse proto.InternalMessageInfo

func (m *QueryGetFilePermissionResponse) GetFilePermission() FilePermission {
	if m != nil {
		return m.FilePermission
	}
	return FilePermission{}
}

type QueryAllFilePermissionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFilePermissionRequest) Reset()         { *m = QueryAllFilePermissionRequest{} }
func (m *QueryAllFilePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllFilePermissionRequest) ProtoMessage()    {}
func (*QueryAllFilePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{8}
}
func (m *QueryAllFilePermissionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFilePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFilePermissionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFilePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFilePermissionRequest.Merge(m, src)
}
func (m *QueryAllFilePermissionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFilePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFilePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFilePermissionRequest proto.InternalMessageInfo

func (m *QueryAllFilePermissionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllFilePermissionResponse struct {
	FilePermission []FilePermission    `protobuf:"bytes,1,rep,name=filePermission,proto3" json:"filePermission"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllFilePermissionResponse) Reset()         { *m = QueryAllFilePermissionResponse{} }
func (m *QueryAllFilePermissionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllFilePermissionResponse) ProtoMessage()    {}
func (*QueryAllFilePermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8f8e8ae022fdd59, []int{9}
}
func (m *QueryAllFilePermissionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllFilePermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllFilePermissionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllFilePermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllFilePermissionResponse.Merge(m, src)
}
func (m *QueryAllFilePermissionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllFilePermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllFilePermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllFilePermissionResponse proto.InternalMessageInfo

func (m *QueryAllFilePermissionResponse) GetFilePermission() []FilePermission {
	if m != nil {
		return m.FilePermission
	}
	return nil
}

func (m *QueryAllFilePermissionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "skillchain.filestorage.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "skillchain.filestorage.QueryParamsResponse")
	proto.RegisterType((*QueryGetFileRecordRequest)(nil), "skillchain.filestorage.QueryGetFileRecordRequest")
	proto.RegisterType((*QueryGetFileRecordResponse)(nil), "skillchain.filestorage.QueryGetFileRecordResponse")
	proto.RegisterType((*QueryAllFileRecordRequest)(nil), "skillchain.filestorage.QueryAllFileRecordRequest")
	proto.RegisterType((*QueryAllFileRecordResponse)(nil), "skillchain.filestorage.QueryAllFileRecordResponse")
	proto.RegisterType((*QueryGetFilePermissionRequest)(nil), "skillchain.filestorage.QueryGetFilePermissionRequest")
	proto.RegisterType((*QueryGetFilePermissionResponse)(nil), "skillchain.filestorage.QueryGetFilePermissionResponse")
	proto.RegisterType((*QueryAllFilePermissionRequest)(nil), "skillchain.filestorage.QueryAllFilePermissionRequest")
	proto.RegisterType((*QueryAllFilePermissionResponse)(nil), "skillchain.filestorage.QueryAllFilePermissionResponse")
}

func init() {
	proto.RegisterFile("skillchain/filestorage/query.proto", fileDescriptor_e8f8e8ae022fdd59)
}

var fileDescriptor_e8f8e8ae022fdd59 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x2d, 0x8d, 0xd4, 0x43, 0x54, 0xea, 0x51, 0x21, 0xb0, 0xc0, 0x54, 0x57, 0xd1,
	0x96, 0x04, 0x7c, 0x4a, 0xaa, 0x00, 0x6b, 0x32, 0xb4, 0x8c, 0xc1, 0x62, 0x40, 0x2c, 0xe8, 0x92,
	0x5e, 0x8c, 0x85, 0xe3, 0x73, 0x7d, 0x6e, 0xd5, 0x0a, 0xb1, 0xb0, 0xb1, 0x21, 0xf1, 0x27, 0xb0,
	0x74, 0x03, 0x89, 0x85, 0x8d, 0xb5, 0x63, 0x25, 0x84, 0xc4, 0x84, 0x50, 0x82, 0xc4, 0xbf, 0x81,
	0x7c, 0x3e, 0xe2, 0xb8, 0xb1, 0x1d, 0x07, 0xba, 0x44, 0xce, 0xf9, 0xfd, 0xf8, 0x7c, 0xdf, 0x7b,
	0xf7, 0x0c, 0xb1, 0x78, 0x61, 0x3b, 0x4e, 0xf7, 0x39, 0xb5, 0x5d, 0xd2, 0xb3, 0x1d, 0x26, 0x02,
	0xee, 0x53, 0x8b, 0x91, 0xbd, 0x7d, 0xe6, 0x1f, 0x19, 0x9e, 0xcf, 0x03, 0x8e, 0xae, 0xc4, 0x36,
	0xc6, 0x98, 0x8d, 0xb6, 0x4c, 0xfb, 0xb6, 0xcb, 0x89, 0xfc, 0x8d, 0x4c, 0xb5, 0x15, 0x8b, 0x5b,
	0x5c, 0x3e, 0x92, 0xf0, 0x49, 0x9d, 0x5e, 0xb7, 0x38, 0xb7, 0x1c, 0x46, 0xa8, 0x67, 0x13, 0xea,
	0xba, 0x3c, 0xa0, 0x81, 0xcd, 0x5d, 0xa1, 0xde, 0x56, 0xba, 0x5c, 0xf4, 0xb9, 0x20, 0x1d, 0x2a,
	0x54, 0x5e, 0x72, 0x50, 0xeb, 0xb0, 0x80, 0xd6, 0x88, 0x47, 0x2d, 0xdb, 0x95, 0xc6, 0xca, 0x76,
	0x2d, 0x03, 0xd7, 0xa3, 0x3e, 0xed, 0xff, 0x0d, 0xb8, 0x99, 0x61, 0x14, 0x3e, 0x3f, 0xf3, 0x59,
	0x97, 0xfb, 0xbb, 0xca, 0xf2, 0x4e, 0x9e, 0xa5, 0xc7, 0xfc, 0xbe, 0x2d, 0xc4, 0x28, 0x39, 0x5e,
	0x81, 0xe8, 0x51, 0x88, 0xd7, 0x96, 0xc9, 0x4c, 0xb6, 0xb7, 0xcf, 0x44, 0x80, 0x9f, 0xc0, 0xcb,
	0x89, 0x53, 0xe1, 0x71, 0x57, 0x30, 0xd4, 0x84, 0xe5, 0x08, 0xea, 0x2a, 0x58, 0x05, 0x9b, 0x17,
	0xeb, 0xba, 0x91, 0x5e, 0x45, 0x23, 0xf2, 0x6b, 0x2d, 0x9e, 0xfc, 0xb8, 0x59, 0x3a, 0xfe, 0xfd,
	0xb1, 0x02, 0x4c, 0xe5, 0x88, 0x6b, 0xf0, 0x9a, 0x8c, 0xbc, 0xc3, 0x82, 0x6d, 0xdb, 0x61, 0xa6,
	0x24, 0x57, 0x69, 0xd1, 0x0a, 0x5c, 0xb0, 0xdd, 0x5d, 0x76, 0x28, 0xc3, 0x2f, 0x9a, 0xd1, 0x1f,
	0xdc, 0x83, 0x5a, 0x9a, 0x8b, 0x62, 0x7a, 0x08, 0x61, 0x6f, 0x74, 0xaa, 0xb8, 0x70, 0x16, 0x57,
	0xec, 0xdf, 0xba, 0x10, 0xb2, 0x99, 0x63, 0xbe, 0xb8, 0xab, 0xd0, 0x9a, 0x8e, 0x33, 0x89, 0xb6,
	0x0d, 0x61, 0xdc, 0x38, 0x95, 0x66, 0xdd, 0x88, 0xba, 0x6c, 0x84, 0x5d, 0x36, 0xa2, 0xe9, 0x52,
	0x5d, 0x36, 0xda, 0xd4, 0x62, 0xca, 0xd7, 0x1c, 0xf3, 0xc4, 0x1f, 0x80, 0x52, 0x73, 0x26, 0x4b,
	0x86, 0x9a, 0xf9, 0x7f, 0x55, 0x83, 0x76, 0x12, 0xc0, 0x73, 0x12, 0x78, 0x63, 0x2a, 0x70, 0x84,
	0x91, 0x20, 0x6e, 0xc0, 0x1b, 0xe3, 0xe5, 0x6f, 0x8f, 0x26, 0x28, 0xbf, 0x6b, 0x07, 0x50, 0xcf,
	0x72, 0x53, 0x5a, 0x1f, 0xc3, 0xa5, 0x5e, 0xe2, 0xcd, 0xa8, 0xac, 0x39, 0x7a, 0x63, 0x6b, 0xa5,
	0xf9, 0x4c, 0x0c, 0x6c, 0x29, 0x5c, 0x55, 0xdf, 0x49, 0xdc, 0xf3, 0xea, 0xe4, 0x17, 0xa0, 0x14,
	0xa6, 0x64, 0xca, 0x51, 0x38, 0xff, 0xbf, 0x0a, 0xcf, 0xad, 0xb3, 0xf5, 0x6f, 0x65, 0xb8, 0x20,
	0x15, 0xa0, 0x37, 0x00, 0x96, 0xa3, 0x3b, 0x8b, 0x2a, 0x59, 0x6c, 0x93, 0x6b, 0x42, 0xab, 0x16,
	0xb2, 0x8d, 0x32, 0xe3, 0xf5, 0xd7, 0x5f, 0x7f, 0xbd, 0x9b, 0x5b, 0x45, 0x3a, 0xc9, 0xdd, 0x77,
	0xe8, 0x18, 0x40, 0x18, 0x4f, 0x36, 0xaa, 0xe5, 0xe6, 0x48, 0x5b, 0x23, 0x5a, 0x7d, 0x16, 0x17,
	0x45, 0xb7, 0x25, 0xe9, 0xee, 0xa2, 0x2a, 0x99, 0xbe, 0x68, 0xc9, 0x4b, 0x39, 0xe2, 0xaf, 0xd0,
	0x7b, 0x00, 0x2f, 0xc5, 0xb1, 0x9a, 0x8e, 0x33, 0x85, 0x36, 0x6d, 0xb3, 0x4c, 0xa1, 0x4d, 0x5d,
	0x13, 0xb8, 0x2a, 0x69, 0x6f, 0xa1, 0xb5, 0x02, 0xb4, 0xe8, 0x33, 0x80, 0x4b, 0xc9, 0xc1, 0x42,
	0x8d, 0x22, 0x15, 0x9a, 0xb8, 0x3a, 0xda, 0xbd, 0x59, 0xdd, 0x14, 0xee, 0x7d, 0x89, 0x5b, 0x43,
	0x84, 0x14, 0xfb, 0x36, 0x8d, 0x0a, 0xfc, 0x09, 0xc0, 0xe5, 0x64, 0xcc, 0xb0, 0xc8, 0x8d, 0x22,
	0x15, 0x9b, 0x95, 0x3e, 0xf3, 0x16, 0x63, 0x22, 0xe9, 0x6f, 0xa3, 0x8d, 0x82, 0xf4, 0xad, 0x07,
	0x27, 0x03, 0x1d, 0x9c, 0x0e, 0x74, 0xf0, 0x73, 0xa0, 0x83, 0xb7, 0x43, 0xbd, 0x74, 0x3a, 0xd4,
	0x4b, 0xdf, 0x87, 0x7a, 0xe9, 0xa9, 0x3e, 0x16, 0xe1, 0x30, 0x11, 0x23, 0x38, 0xf2, 0x98, 0xe8,
	0x94, 0xe5, 0x47, 0x79, 0xeb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x6c, 0xfa, 0xda, 0xc2,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of FileRecord items.
	FileRecord(ctx context.Context, in *QueryGetFileRecordRequest, opts ...grpc.CallOption) (*QueryGetFileRecordResponse, error)
	FileRecordAll(ctx context.Context, in *QueryAllFileRecordRequest, opts ...grpc.CallOption) (*QueryAllFileRecordResponse, error)
	// Queries a list of FilePermission items.
	FilePermission(ctx context.Context, in *QueryGetFilePermissionRequest, opts ...grpc.CallOption) (*QueryGetFilePermissionResponse, error)
	FilePermissionAll(ctx context.Context, in *QueryAllFilePermissionRequest, opts ...grpc.CallOption) (*QueryAllFilePermissionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/skillchain.filestorage.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FileRecord(ctx context.Context, in *QueryGetFileRecordRequest, opts ...grpc.CallOption) (*QueryGetFileRecordResponse, error) {
	out := new(QueryGetFileRecordResponse)
	err := c.cc.Invoke(ctx, "/skillchain.filestorage.Query/FileRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FileRecordAll(ctx context.Context, in *QueryAllFileRecordRequest, opts ...grpc.CallOption) (*QueryAllFileRecordResponse, error) {
	out := new(QueryAllFileRecordResponse)
	err := c.cc.Invoke(ctx, "/skillchain.filestorage.Query/FileRecordAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FilePermission(ctx context.Context, in *QueryGetFilePermissionRequest, opts ...grpc.CallOption) (*QueryGetFilePermissionResponse, error) {
	out := new(QueryGetFilePermissionResponse)
	err := c.cc.Invoke(ctx, "/skillchain.filestorage.Query/FilePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FilePermissionAll(ctx context.Context, in *QueryAllFilePermissionRequest, opts ...grpc.CallOption) (*QueryAllFilePermissionResponse, error) {
	out := new(QueryAllFilePermissionResponse)
	err := c.cc.Invoke(ctx, "/skillchain.filestorage.Query/FilePermissionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of FileRecord items.
	FileRecord(context.Context, *QueryGetFileRecordRequest) (*QueryGetFileRecordResponse, error)
	FileRecordAll(context.Context, *QueryAllFileRecordRequest) (*QueryAllFileRecordResponse, error)
	// Queries a list of FilePermission items.
	FilePermission(context.Context, *QueryGetFilePermissionRequest) (*QueryGetFilePermissionResponse, error)
	FilePermissionAll(context.Context, *QueryAllFilePermissionRequest) (*QueryAllFilePermissionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) FileRecord(ctx context.Context, req *QueryGetFileRecordRequest) (*QueryGetFileRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRecord not implemented")
}
func (*UnimplementedQueryServer) FileRecordAll(ctx context.Context, req *QueryAllFileRecordRequest) (*QueryAllFileRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRecordAll not implemented")
}
func (*UnimplementedQueryServer) FilePermission(ctx context.Context, req *QueryGetFilePermissionRequest) (*QueryGetFilePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilePermission not implemented")
}
func (*UnimplementedQueryServer) FilePermissionAll(ctx context.Context, req *QueryAllFilePermissionRequest) (*QueryAllFilePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilePermissionAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.filestorage.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FileRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetFileRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FileRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.filestorage.Query/FileRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FileRecord(ctx, req.(*QueryGetFileRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FileRecordAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFileRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FileRecordAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.filestorage.Query/FileRecordAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FileRecordAll(ctx, req.(*QueryAllFileRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FilePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetFilePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FilePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.filestorage.Query/FilePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FilePermission(ctx, req.(*QueryGetFilePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FilePermissionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFilePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FilePermissionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.filestorage.Query/FilePermissionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FilePermissionAll(ctx, req.(*QueryAllFilePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skillchain.filestorage.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "FileRecord",
			Handler:    _Query_FileRecord_Handler,
		},
		{
			MethodName: "FileRecordAll",
			Handler:    _Query_FileRecordAll_Handler,
		},
		{
			MethodName: "FilePermission",
			Handler:    _Query_FilePermission_Handler,
		},
		{
			MethodName: "FilePermissionAll",
			Handler:    _Query_FilePermissionAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skillchain/filestorage/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetFileRecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFileRecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFileRecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFileRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFileRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFileRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FileRecord.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllFileRecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFileRecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFileRecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllFileRecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFileRecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFileRecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FileRecord) > 0 {
		for iNdEx := len(m.FileRecord) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FileRecord[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFilePermissionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFilePermissionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFilePermissionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetFilePermissionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetFilePermissionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetFilePermissionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FilePermission.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllFilePermissionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFilePermissionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFilePermissionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllFilePermissionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllFilePermissionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllFilePermissionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FilePermission) > 0 {
		for iNdEx := len(m.FilePermission) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FilePermission[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetFileRecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFileRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FileRecord.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllFileRecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllFileRecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FileRecord) > 0 {
		for _, e := range m.FileRecord {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFilePermissionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetFilePermissionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FilePermission.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllFilePermissionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllFilePermissionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FilePermission) > 0 {
		for _, e := range m.FilePermission {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFileRecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFileRecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFileRecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFileRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFileRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFileRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileRecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FileRecord.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFileRecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFileRecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFileRecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFileRecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFileRecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFileRecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileRecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileRecord = append(m.FileRecord, FileRecord{})
			if err := m.FileRecord[len(m.FileRecord)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFilePermissionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFilePermissionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFilePermissionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetFilePermissionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetFilePermissionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetFilePermissionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilePermission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FilePermission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFilePermissionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFilePermissionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFilePermissionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllFilePermissionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllFilePermissionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllFilePermissionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilePermission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FilePermission = append(m.FilePermission, FilePermission{})
			if err := m.FilePermission[len(m.FilePermission)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
