// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package profile

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_SkillEndorsement                   protoreflect.MessageDescriptor
	fd_SkillEndorsement_index             protoreflect.FieldDescriptor
	fd_SkillEndorsement_endorser          protoreflect.FieldDescriptor
	fd_SkillEndorsement_targetUser        protoreflect.FieldDescriptor
	fd_SkillEndorsement_skillName         protoreflect.FieldDescriptor
	fd_SkillEndorsement_endorsementType   protoreflect.FieldDescriptor
	fd_SkillEndorsement_comment           protoreflect.FieldDescriptor
	fd_SkillEndorsement_createdAt         protoreflect.FieldDescriptor
	fd_SkillEndorsement_skillTokensStaked protoreflect.FieldDescriptor
	fd_SkillEndorsement_creator           protoreflect.FieldDescriptor
)

func init() {
	file_skillchain_profile_skill_endorsement_proto_init()
	md_SkillEndorsement = File_skillchain_profile_skill_endorsement_proto.Messages().ByName("SkillEndorsement")
	fd_SkillEndorsement_index = md_SkillEndorsement.Fields().ByName("index")
	fd_SkillEndorsement_endorser = md_SkillEndorsement.Fields().ByName("endorser")
	fd_SkillEndorsement_targetUser = md_SkillEndorsement.Fields().ByName("targetUser")
	fd_SkillEndorsement_skillName = md_SkillEndorsement.Fields().ByName("skillName")
	fd_SkillEndorsement_endorsementType = md_SkillEndorsement.Fields().ByName("endorsementType")
	fd_SkillEndorsement_comment = md_SkillEndorsement.Fields().ByName("comment")
	fd_SkillEndorsement_createdAt = md_SkillEndorsement.Fields().ByName("createdAt")
	fd_SkillEndorsement_skillTokensStaked = md_SkillEndorsement.Fields().ByName("skillTokensStaked")
	fd_SkillEndorsement_creator = md_SkillEndorsement.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_SkillEndorsement)(nil)

type fastReflection_SkillEndorsement SkillEndorsement

func (x *SkillEndorsement) ProtoReflect() protoreflect.Message {
	return (*fastReflection_SkillEndorsement)(x)
}

func (x *SkillEndorsement) slowProtoReflect() protoreflect.Message {
	mi := &file_skillchain_profile_skill_endorsement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_SkillEndorsement_messageType fastReflection_SkillEndorsement_messageType
var _ protoreflect.MessageType = fastReflection_SkillEndorsement_messageType{}

type fastReflection_SkillEndorsement_messageType struct{}

func (x fastReflection_SkillEndorsement_messageType) Zero() protoreflect.Message {
	return (*fastReflection_SkillEndorsement)(nil)
}
func (x fastReflection_SkillEndorsement_messageType) New() protoreflect.Message {
	return new(fastReflection_SkillEndorsement)
}
func (x fastReflection_SkillEndorsement_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_SkillEndorsement
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_SkillEndorsement) Descriptor() protoreflect.MessageDescriptor {
	return md_SkillEndorsement
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_SkillEndorsement) Type() protoreflect.MessageType {
	return _fastReflection_SkillEndorsement_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_SkillEndorsement) New() protoreflect.Message {
	return new(fastReflection_SkillEndorsement)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_SkillEndorsement) Interface() protoreflect.ProtoMessage {
	return (*SkillEndorsement)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_SkillEndorsement) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_SkillEndorsement_index, value) {
			return
		}
	}
	if x.Endorser != "" {
		value := protoreflect.ValueOfString(x.Endorser)
		if !f(fd_SkillEndorsement_endorser, value) {
			return
		}
	}
	if x.TargetUser != "" {
		value := protoreflect.ValueOfString(x.TargetUser)
		if !f(fd_SkillEndorsement_targetUser, value) {
			return
		}
	}
	if x.SkillName != "" {
		value := protoreflect.ValueOfString(x.SkillName)
		if !f(fd_SkillEndorsement_skillName, value) {
			return
		}
	}
	if x.EndorsementType != "" {
		value := protoreflect.ValueOfString(x.EndorsementType)
		if !f(fd_SkillEndorsement_endorsementType, value) {
			return
		}
	}
	if x.Comment != "" {
		value := protoreflect.ValueOfString(x.Comment)
		if !f(fd_SkillEndorsement_comment, value) {
			return
		}
	}
	if x.CreatedAt != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CreatedAt)
		if !f(fd_SkillEndorsement_createdAt, value) {
			return
		}
	}
	if x.SkillTokensStaked != uint64(0) {
		value := protoreflect.ValueOfUint64(x.SkillTokensStaked)
		if !f(fd_SkillEndorsement_skillTokensStaked, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_SkillEndorsement_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_SkillEndorsement) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		return x.Index != ""
	case "skillchain.profile.SkillEndorsement.endorser":
		return x.Endorser != ""
	case "skillchain.profile.SkillEndorsement.targetUser":
		return x.TargetUser != ""
	case "skillchain.profile.SkillEndorsement.skillName":
		return x.SkillName != ""
	case "skillchain.profile.SkillEndorsement.endorsementType":
		return x.EndorsementType != ""
	case "skillchain.profile.SkillEndorsement.comment":
		return x.Comment != ""
	case "skillchain.profile.SkillEndorsement.createdAt":
		return x.CreatedAt != uint64(0)
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		return x.SkillTokensStaked != uint64(0)
	case "skillchain.profile.SkillEndorsement.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SkillEndorsement) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		x.Index = ""
	case "skillchain.profile.SkillEndorsement.endorser":
		x.Endorser = ""
	case "skillchain.profile.SkillEndorsement.targetUser":
		x.TargetUser = ""
	case "skillchain.profile.SkillEndorsement.skillName":
		x.SkillName = ""
	case "skillchain.profile.SkillEndorsement.endorsementType":
		x.EndorsementType = ""
	case "skillchain.profile.SkillEndorsement.comment":
		x.Comment = ""
	case "skillchain.profile.SkillEndorsement.createdAt":
		x.CreatedAt = uint64(0)
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		x.SkillTokensStaked = uint64(0)
	case "skillchain.profile.SkillEndorsement.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_SkillEndorsement) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.endorser":
		value := x.Endorser
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.targetUser":
		value := x.TargetUser
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.skillName":
		value := x.SkillName
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.endorsementType":
		value := x.EndorsementType
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.comment":
		value := x.Comment
		return protoreflect.ValueOfString(value)
	case "skillchain.profile.SkillEndorsement.createdAt":
		value := x.CreatedAt
		return protoreflect.ValueOfUint64(value)
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		value := x.SkillTokensStaked
		return protoreflect.ValueOfUint64(value)
	case "skillchain.profile.SkillEndorsement.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SkillEndorsement) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		x.Index = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.endorser":
		x.Endorser = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.targetUser":
		x.TargetUser = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.skillName":
		x.SkillName = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.endorsementType":
		x.EndorsementType = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.comment":
		x.Comment = value.Interface().(string)
	case "skillchain.profile.SkillEndorsement.createdAt":
		x.CreatedAt = value.Uint()
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		x.SkillTokensStaked = value.Uint()
	case "skillchain.profile.SkillEndorsement.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SkillEndorsement) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		panic(fmt.Errorf("field index of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.endorser":
		panic(fmt.Errorf("field endorser of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.targetUser":
		panic(fmt.Errorf("field targetUser of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.skillName":
		panic(fmt.Errorf("field skillName of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.endorsementType":
		panic(fmt.Errorf("field endorsementType of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.comment":
		panic(fmt.Errorf("field comment of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.createdAt":
		panic(fmt.Errorf("field createdAt of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		panic(fmt.Errorf("field skillTokensStaked of message skillchain.profile.SkillEndorsement is not mutable"))
	case "skillchain.profile.SkillEndorsement.creator":
		panic(fmt.Errorf("field creator of message skillchain.profile.SkillEndorsement is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_SkillEndorsement) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "skillchain.profile.SkillEndorsement.index":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.endorser":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.targetUser":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.skillName":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.endorsementType":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.comment":
		return protoreflect.ValueOfString("")
	case "skillchain.profile.SkillEndorsement.createdAt":
		return protoreflect.ValueOfUint64(uint64(0))
	case "skillchain.profile.SkillEndorsement.skillTokensStaked":
		return protoreflect.ValueOfUint64(uint64(0))
	case "skillchain.profile.SkillEndorsement.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: skillchain.profile.SkillEndorsement"))
		}
		panic(fmt.Errorf("message skillchain.profile.SkillEndorsement does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_SkillEndorsement) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in skillchain.profile.SkillEndorsement", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_SkillEndorsement) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_SkillEndorsement) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_SkillEndorsement) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_SkillEndorsement) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*SkillEndorsement)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Endorser)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.TargetUser)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SkillName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EndorsementType)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Comment)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CreatedAt != 0 {
			n += 1 + runtime.Sov(uint64(x.CreatedAt))
		}
		if x.SkillTokensStaked != 0 {
			n += 1 + runtime.Sov(uint64(x.SkillTokensStaked))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*SkillEndorsement)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x4a
		}
		if x.SkillTokensStaked != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SkillTokensStaked))
			i--
			dAtA[i] = 0x40
		}
		if x.CreatedAt != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CreatedAt))
			i--
			dAtA[i] = 0x38
		}
		if len(x.Comment) > 0 {
			i -= len(x.Comment)
			copy(dAtA[i:], x.Comment)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Comment)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.EndorsementType) > 0 {
			i -= len(x.EndorsementType)
			copy(dAtA[i:], x.EndorsementType)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EndorsementType)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.SkillName) > 0 {
			i -= len(x.SkillName)
			copy(dAtA[i:], x.SkillName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SkillName)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.TargetUser) > 0 {
			i -= len(x.TargetUser)
			copy(dAtA[i:], x.TargetUser)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TargetUser)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Endorser) > 0 {
			i -= len(x.Endorser)
			copy(dAtA[i:], x.Endorser)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Endorser)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*SkillEndorsement)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: SkillEndorsement: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: SkillEndorsement: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Endorser", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Endorser = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TargetUser", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TargetUser = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SkillName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SkillName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EndorsementType", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EndorsementType = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Comment = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
				}
				x.CreatedAt = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CreatedAt |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SkillTokensStaked", wireType)
				}
				x.SkillTokensStaked = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SkillTokensStaked |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: skillchain/profile/skill_endorsement.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillEndorsement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index             string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Endorser          string `protobuf:"bytes,2,opt,name=endorser,proto3" json:"endorser,omitempty"`
	TargetUser        string `protobuf:"bytes,3,opt,name=targetUser,proto3" json:"targetUser,omitempty"`
	SkillName         string `protobuf:"bytes,4,opt,name=skillName,proto3" json:"skillName,omitempty"`
	EndorsementType   string `protobuf:"bytes,5,opt,name=endorsementType,proto3" json:"endorsementType,omitempty"`
	Comment           string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt         uint64 `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	SkillTokensStaked uint64 `protobuf:"varint,8,opt,name=skillTokensStaked,proto3" json:"skillTokensStaked,omitempty"`
	Creator           string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *SkillEndorsement) Reset() {
	*x = SkillEndorsement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skillchain_profile_skill_endorsement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEndorsement) ProtoMessage() {}

// Deprecated: Use SkillEndorsement.ProtoReflect.Descriptor instead.
func (*SkillEndorsement) Descriptor() ([]byte, []int) {
	return file_skillchain_profile_skill_endorsement_proto_rawDescGZIP(), []int{0}
}

func (x *SkillEndorsement) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *SkillEndorsement) GetEndorser() string {
	if x != nil {
		return x.Endorser
	}
	return ""
}

func (x *SkillEndorsement) GetTargetUser() string {
	if x != nil {
		return x.TargetUser
	}
	return ""
}

func (x *SkillEndorsement) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillEndorsement) GetEndorsementType() string {
	if x != nil {
		return x.EndorsementType
	}
	return ""
}

func (x *SkillEndorsement) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SkillEndorsement) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SkillEndorsement) GetSkillTokensStaked() uint64 {
	if x != nil {
		return x.SkillTokensStaked
	}
	return 0
}

func (x *SkillEndorsement) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_skillchain_profile_skill_endorsement_proto protoreflect.FileDescriptor

var file_skillchain_profile_skill_endorsement_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0xac, 0x02, 0x0a, 0x10, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x11, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x53,
	0x74, 0x61, 0x6b, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42,
	0xbb, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x15, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x21, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0xa2, 0x02, 0x03, 0x53, 0x50, 0x58, 0xaa, 0x02, 0x12, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0xca, 0x02, 0x12, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0xe2, 0x02, 0x1e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x5c, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x13, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_skillchain_profile_skill_endorsement_proto_rawDescOnce sync.Once
	file_skillchain_profile_skill_endorsement_proto_rawDescData = file_skillchain_profile_skill_endorsement_proto_rawDesc
)

func file_skillchain_profile_skill_endorsement_proto_rawDescGZIP() []byte {
	file_skillchain_profile_skill_endorsement_proto_rawDescOnce.Do(func() {
		file_skillchain_profile_skill_endorsement_proto_rawDescData = protoimpl.X.CompressGZIP(file_skillchain_profile_skill_endorsement_proto_rawDescData)
	})
	return file_skillchain_profile_skill_endorsement_proto_rawDescData
}

var file_skillchain_profile_skill_endorsement_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_skillchain_profile_skill_endorsement_proto_goTypes = []interface{}{
	(*SkillEndorsement)(nil), // 0: skillchain.profile.SkillEndorsement
}
var file_skillchain_profile_skill_endorsement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_skillchain_profile_skill_endorsement_proto_init() }
func file_skillchain_profile_skill_endorsement_proto_init() {
	if File_skillchain_profile_skill_endorsement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_skillchain_profile_skill_endorsement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillEndorsement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skillchain_profile_skill_endorsement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skillchain_profile_skill_endorsement_proto_goTypes,
		DependencyIndexes: file_skillchain_profile_skill_endorsement_proto_depIdxs,
		MessageInfos:      file_skillchain_profile_skill_endorsement_proto_msgTypes,
	}.Build()
	File_skillchain_profile_skill_endorsement_proto = out.File
	file_skillchain_profile_skill_endorsement_proto_rawDesc = nil
	file_skillchain_profile_skill_endorsement_proto_goTypes = nil
	file_skillchain_profile_skill_endorsement_proto_depIdxs = nil
}
