// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/profile/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Request to get one profile
type QueryShowProfileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *QueryShowProfileRequest) Reset()         { *m = QueryShowProfileRequest{} }
func (m *QueryShowProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowProfileRequest) ProtoMessage()    {}
func (*QueryShowProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f9e7c6ae31292b, []int{0}
}
func (m *QueryShowProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowProfileRequest.Merge(m, src)
}
func (m *QueryShowProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowProfileRequest proto.InternalMessageInfo

func (m *QueryShowProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Response containing the profile
type QueryShowProfileResponse struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bio      string `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
}

func (m *QueryShowProfileResponse) Reset()         { *m = QueryShowProfileResponse{} }
func (m *QueryShowProfileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowProfileResponse) ProtoMessage()    {}
func (*QueryShowProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f9e7c6ae31292b, []int{1}
}
func (m *QueryShowProfileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowProfileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowProfileResponse.Merge(m, src)
}
func (m *QueryShowProfileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowProfileResponse proto.InternalMessageInfo

func (m *QueryShowProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryShowProfileResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

type QueryListProfileRequest struct {
}

func (m *QueryListProfileRequest) Reset()         { *m = QueryListProfileRequest{} }
func (m *QueryListProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListProfileRequest) ProtoMessage()    {}
func (*QueryListProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f9e7c6ae31292b, []int{2}
}
func (m *QueryListProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListProfileRequest.Merge(m, src)
}
func (m *QueryListProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListProfileRequest proto.InternalMessageInfo

type QueryListProfileResponse struct {
	Profiles []*Profile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (m *QueryListProfileResponse) Reset()         { *m = QueryListProfileResponse{} }
func (m *QueryListProfileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListProfileResponse) ProtoMessage()    {}
func (*QueryListProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14f9e7c6ae31292b, []int{3}
}
func (m *QueryListProfileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListProfileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListProfileResponse.Merge(m, src)
}
func (m *QueryListProfileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListProfileResponse proto.InternalMessageInfo

func (m *QueryListProfileResponse) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryShowProfileRequest)(nil), "skillchain.profile.QueryShowProfileRequest")
	proto.RegisterType((*QueryShowProfileResponse)(nil), "skillchain.profile.QueryShowProfileResponse")
	proto.RegisterType((*QueryListProfileRequest)(nil), "skillchain.profile.QueryListProfileRequest")
	proto.RegisterType((*QueryListProfileResponse)(nil), "skillchain.profile.QueryListProfileResponse")
}

func init() { proto.RegisterFile("skillchain/profile/query.proto", fileDescriptor_14f9e7c6ae31292b) }

var fileDescriptor_14f9e7c6ae31292b = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x3f, 0x8f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0xab, 0x38, 0x1d, 0xee, 0x02, 0x16, 0x12, 0x21, 0xa0, 0x50, 0x65, 0x80, 0xea,
	0x38, 0xc5, 0x77, 0x2d, 0x7f, 0x76, 0x58, 0x18, 0x8a, 0x54, 0xda, 0x8d, 0x05, 0x39, 0x95, 0x49,
	0x2d, 0x12, 0xbf, 0x69, 0xec, 0x00, 0x15, 0x62, 0x61, 0x65, 0x41, 0x62, 0x47, 0x7c, 0x1c, 0xc6,
	0x4a, 0x2c, 0xb0, 0xa1, 0x96, 0x0f, 0x82, 0xe2, 0xb8, 0xa5, 0x55, 0xd2, 0x96, 0x25, 0xb1, 0xfd,
	0x3e, 0xcf, 0xfb, 0xfe, 0xe2, 0x47, 0xc1, 0x9e, 0x7a, 0x2d, 0xe2, 0x78, 0x3c, 0x61, 0x42, 0xd2,
	0x34, 0x83, 0x57, 0x22, 0xe6, 0x74, 0x9a, 0xf3, 0x6c, 0x16, 0xa4, 0x19, 0x68, 0x20, 0xe4, 0x5f,
	0x3d, 0xb0, 0x75, 0xf7, 0x2a, 0x4b, 0x84, 0x04, 0x6a, 0x9e, 0xa5, 0xcc, 0xbd, 0x16, 0x41, 0x04,
	0x66, 0x49, 0x8b, 0x95, 0x3d, 0xbd, 0x15, 0x01, 0x44, 0x31, 0xa7, 0x2c, 0x15, 0x94, 0x49, 0x09,
	0x9a, 0x69, 0x01, 0x52, 0xd9, 0xea, 0xe9, 0x18, 0x54, 0x02, 0x8a, 0x86, 0x4c, 0xd9, 0x99, 0xf4,
	0xcd, 0x45, 0xc8, 0x35, 0xbb, 0xa0, 0x29, 0x8b, 0x84, 0x34, 0x62, 0xab, 0xbd, 0x5d, 0x83, 0x99,
	0xb2, 0x8c, 0x25, 0xab, 0x66, 0xed, 0x3a, 0x41, 0xf9, 0x2e, 0x15, 0xfe, 0x03, 0x7c, 0xfd, 0x79,
	0x31, 0x64, 0x34, 0x81, 0xb7, 0x83, 0xb2, 0x32, 0xe4, 0xd3, 0x9c, 0x2b, 0x4d, 0x5c, 0x7c, 0x92,
	0x2b, 0x9e, 0x49, 0x96, 0x70, 0x07, 0xb5, 0x51, 0xe7, 0xf2, 0x70, 0xbd, 0xf7, 0x9f, 0x62, 0xa7,
	0x6a, 0x53, 0x29, 0x48, 0xc5, 0xf7, 0xf9, 0xc8, 0x15, 0xdc, 0x0c, 0x05, 0x38, 0x47, 0xe6, 0xb8,
	0x58, 0xfa, 0x37, 0x2c, 0x40, 0x5f, 0x28, 0xbd, 0x0d, 0xe0, 0x8f, 0xec, 0x90, 0xad, 0x92, 0x1d,
	0xf2, 0x08, 0x9f, 0xd8, 0x0f, 0x51, 0x0e, 0x6a, 0x37, 0x3b, 0xad, 0xee, 0xcd, 0xa0, 0x1a, 0x4a,
	0xb0, 0xb2, 0xad, 0xc5, 0xdd, 0x5f, 0x4d, 0x7c, 0xc9, 0x74, 0x25, 0x9f, 0x10, 0x3e, 0x1e, 0x98,
	0xdb, 0x22, 0x77, 0xea, 0xbc, 0x46, 0x55, 0x0a, 0x2c, 0x91, 0x7b, 0xf7, 0xa0, 0xae, 0xc4, 0xf3,
	0xcf, 0x3f, 0xfe, 0xf8, 0xf3, 0xe5, 0xe8, 0x94, 0x74, 0xe8, 0xa8, 0x30, 0x3c, 0x29, 0x0c, 0x7d,
	0x16, 0xd2, 0x9d, 0x81, 0x91, 0xaf, 0x08, 0xb7, 0x36, 0x6e, 0x93, 0xdc, 0xdb, 0x39, 0xaa, 0x1a,
	0x95, 0x7b, 0xf6, 0x7f, 0x62, 0x0b, 0x77, 0xdf, 0xc0, 0x05, 0xe4, 0xec, 0x30, 0xdc, 0xfb, 0x55,
	0x72, 0x1f, 0xc8, 0x37, 0x84, 0x5b, 0x1b, 0x49, 0xec, 0x01, 0xac, 0x46, 0xb9, 0x07, 0xb0, 0x26,
	0x5c, 0xff, 0xa1, 0x01, 0x3c, 0x27, 0xc1, 0x61, 0xc0, 0x58, 0x28, 0xfd, 0xd2, 0x6e, 0x1e, 0x3f,
	0xfb, 0xbe, 0xf0, 0xd0, 0x7c, 0xe1, 0xa1, 0xdf, 0x0b, 0x0f, 0x7d, 0x5e, 0x7a, 0x8d, 0xf9, 0xd2,
	0x6b, 0xfc, 0x5c, 0x7a, 0x8d, 0x17, 0xbd, 0x48, 0xe8, 0x49, 0x1e, 0x06, 0x63, 0x48, 0x76, 0xf7,
	0x7c, 0xb7, 0xee, 0xaa, 0x67, 0x29, 0x57, 0xe1, 0xb1, 0xf9, 0x45, 0x7a, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xee, 0xcb, 0xcf, 0x7e, 0x0e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Get a specific profile by username
	ShowProfile(ctx context.Context, in *QueryShowProfileRequest, opts ...grpc.CallOption) (*QueryShowProfileResponse, error)
	// Queries a list of ListProfile items.
	ListProfile(ctx context.Context, in *QueryListProfileRequest, opts ...grpc.CallOption) (*QueryListProfileResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/skillchain.profile.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowProfile(ctx context.Context, in *QueryShowProfileRequest, opts ...grpc.CallOption) (*QueryShowProfileResponse, error) {
	out := new(QueryShowProfileResponse)
	err := c.cc.Invoke(ctx, "/skillchain.profile.Query/ShowProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListProfile(ctx context.Context, in *QueryListProfileRequest, opts ...grpc.CallOption) (*QueryListProfileResponse, error) {
	out := new(QueryListProfileResponse)
	err := c.cc.Invoke(ctx, "/skillchain.profile.Query/ListProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Get a specific profile by username
	ShowProfile(context.Context, *QueryShowProfileRequest) (*QueryShowProfileResponse, error)
	// Queries a list of ListProfile items.
	ListProfile(context.Context, *QueryListProfileRequest) (*QueryListProfileResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ShowProfile(ctx context.Context, req *QueryShowProfileRequest) (*QueryShowProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowProfile not implemented")
}
func (*UnimplementedQueryServer) ListProfile(ctx context.Context, req *QueryListProfileRequest) (*QueryListProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfile not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.profile.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.profile.Query/ShowProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowProfile(ctx, req.(*QueryShowProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skillchain.profile.Query/ListProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListProfile(ctx, req.(*QueryListProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skillchain.profile.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowProfile",
			Handler:    _Query_ShowProfile_Handler,
		},
		{
			MethodName: "ListProfile",
			Handler:    _Query_ListProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skillchain/profile/query.proto",
}

func (m *QueryShowProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowProfileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowProfileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowProfileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bio) > 0 {
		i -= len(m.Bio)
		copy(dAtA[i:], m.Bio)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Bio)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListProfileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListProfileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListProfileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Profiles) > 0 {
		for iNdEx := len(m.Profiles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Profiles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryShowProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowProfileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Bio)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListProfileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Profiles) > 0 {
		for _, e := range m.Profiles {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryShowProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowProfileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowProfileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowProfileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListProfileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListProfileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListProfileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Profiles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Profiles = append(m.Profiles, &Profile{})
			if err := m.Profiles[len(m.Profiles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
